version: '2'

services:
  discovery:
    image: xelitalabs/discovery-management
    ports:
      - "9999:9999"
    environment:
      - SPRING_PROFILES_ACTIVE=DOCKER

  configuration:
    image: xelitalabs/configuration-management
    ports:
      - "9898:9898"
    environment:
      - SPRING_PROFILES_ACTIVE=DOCKER
    depends_on:
      - discovery
    entrypoint: bash ./docker_wait.sh -t 60 discovery:9999 -- java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
